#!/usr/bin/env bash

hostName="$1"

if [[ "${hostName}" == "" ]]; then
	echo "Host required to deploy a certificate."
	exit
fi

FILE_CA_CERTIFICATE="${DIR_CERTIFICATES}/ca/ca.pem"
FILE_CA_KEY="${DIR_CERTIFICATES}/ca/ca-key.pem"

targetDirectory="${DIR_CERTIFICATES}/${hostName}"
request="${targetDirectory}/request.md"
certificate="${targetDirectory}/${hostName}.pem"
privateKey="${targetDirectory}/${hostName}-key.pem"

publicIP=$(cat ${request} | grep 'publicIP' | awk '{print $2}')
destination="core@${publicIP}:"

echo "Deploying certificate..."

chmod 0644 ${privateKey}
scp ${FILE_CA_CERTIFICATE} ${certificate} ${privateKey} ${destination}
echo "
Certificate files deployed to ${destination}.
	${certificate}
	${privateKey}
"
