#!/usr/bin/env bash

hostName="$1"
privateIP="$2"
publicIP="$3"

if [[ ${hostName} == "" ]]; then
	echo "Host required to generate a certificate request."
	exit
fi

if [[ ${privateIP} == "" ]]; then
	echo "Private IP of host machine required to generate a certificate request."
	exit
fi

if [[ ${publicIP} == "" ]]; then
	echo "Public IP of host machine required to generate a certificate request."
	exit
fi

targetDirectory="${DIR_CERTIFICATES}/${hostName}"
request="${targetDirectory}/request.md"
csr="${targetDirectory}/csr.json"

echo "Generating certificate request.md and CSR..."

mkdir -p ${targetDirectory}

echo "
host: ${hostName}
privateIP: ${privateIP}
publicIP: ${publicIP}
" > ${request}
echo "${request} created."

cp ${FILE_CSR_TEMPLATE} ${csr}
sed -i s/\{\{hostName\}\}/${hostName}/g ${csr}
sed -i s/\{\{privateIP\}\}/${privateIP}/g ${csr}
echo "${csr} created."
