#!/usr/bin/env bash

FILE_CA_CSR="${DIR_CERTIFICATES}/ca/csr.json"

echo "Generating Certificate Authority..."

$(dirname ${BASH_SOURCE[0]})/generateCsr ca 127.0.0.1
echo "CSR generated."

cd /home/certificates/ca
cfssl gencert -config ${FILE_CA_CONFIG} -initca ${FILE_CA_CSR} | cfssljson -bare ca -
echo "Certificate Authority generated."
